import {
  faReact,
  faNodeJs,
  faLaravel,
  faGitAlt,
  faJsSquare,
} from '@fortawesome/free-brands-svg-icons';
import {
  faBook,
  faAtom,
  faCode,
  faDatabase,
  faCogs,
  faNetworkWired,
  faChartLine,
  faGamepad,
  faPuzzlePiece,
  faGraduationCap,
  faThermometerHalf,
  faDoorOpen,
  faTrain,
  faShieldAlt,
  faTerminal,
  faRobot,
  faBrain,
  faFilePdf,
  faSeedling,
  faStore,
  faNewspaper,
} from '@fortawesome/free-solid-svg-icons';
import { PortfolioCategory } from './types';

// Reglas: solo links PÚBLICOS (apps en vivo o repos públicos). Títulos = solo el nombre;
// el detalle va en la descripción. Visibles (important: true) = solo los más pulcos;
// el resto queda presente pero oculto tras "Ver más".
export const portfolioCategories: PortfolioCategory[] = [
  {
    name: 'portfolio.programming',
    icon: faCode,
    projects: [
      // --- Visibles: lo más ambicioso/pulcro y sistemas en producción ---
      {
        name: 'portfolio.project.symploqueCrm',
        link: 'https://github.com/stevenvo780/symploque-crm',
        description: 'portfolio.description.symploqueCrm',
        icon: faChartLine,
        important: true,
      },
      {
        name: 'portfolio.project.stLanguage',
        link: 'https://github.com/stevenvo780/ST',
        description: 'portfolio.description.stLanguage',
        icon: faTerminal,
        important: true,
      },
      {
        name: 'portfolio.project.agora',
        link: 'https://agora.elenxos.com',
        description: 'portfolio.description.agora',
        icon: faReact,
        important: true,
      },
      {
        name: 'portfolio.project.mcpDelegateAgents',
        link: 'https://github.com/stevenvo780/MCP-delegate-agents',
        description: 'portfolio.description.mcpDelegateAgents',
        icon: faRobot,
        important: true,
      },
      {
        name: 'portfolio.project.autoLogic',
        link: 'https://github.com/stevenvo780/auto.logic',
        description: 'portfolio.description.autoLogic',
        icon: faBrain,
        important: true,
      },
      {
        name: 'portfolio.project.educacionCooperativa',
        link: 'https://github.com/stevenvo780/EducacionCooperativa',
        description: 'portfolio.description.educacionCooperativa',
        icon: faReact,
        important: true,
      },
      {
        name: 'portfolio.project.graf',
        link: 'https://totalpedidosv2-client.vercel.app',
        description: 'portfolio.description.graf',
        icon: faStore,
        important: true,
      },
      {
        name: 'portfolio.project.sinergiaPos',
        link: 'https://pos-frond.vercel.app',
        description: 'portfolio.description.sinergiaPos',
        icon: faCogs,
        important: true,
      },
      {
        name: 'portfolio.project.fiarFront',
        link: 'https://fiar-front.vercel.app',
        description: 'portfolio.description.fiarFront',
        icon: faChartLine,
        important: true,
      },
      {
        name: 'portfolio.project.ultimateTerminal',
        link: 'https://github.com/stevenvo780/ultimate-terminal',
        description: 'portfolio.description.ultimateTerminal',
        icon: faTerminal,
        important: true,
      },
      {
        name: 'portfolio.project.cristinaCms',
        link: 'https://cristina-cms.vercel.app',
        description: 'portfolio.description.cristinaCms',
        icon: faNewspaper,
        important: true,
      },
      {
        name: 'portfolio.project.cafeteriaDelCaosFrontNext',
        link: 'https://cafeteria-del-caos-front-next.vercel.app',
        description: 'portfolio.description.cafeteriaDelCaosFrontNext',
        icon: faReact,
        important: true,
      },
      // --- Ocultos: IA / backends / herramientas (links públicos) ---
      {
        name: 'portfolio.project.jarvisIaV2',
        link: 'https://github.com/stevenvo780/jarvisIAV2',
        description: 'portfolio.description.jarvisIaV2',
        icon: faRobot,
        important: false,
      },
      {
        name: 'portfolio.project.emw',
        link: 'https://emw.humanizar.cloud/',
        description: 'portfolio.description.emw',
        icon: faCogs,
        important: false,
      },
      {
        name: 'portfolio.project.convertPdfToMarkdownIa',
        link: 'https://github.com/stevenvo780/ConvertPDFToMarkdownIA',
        description: 'portfolio.description.convertPdfToMarkdownIa',
        icon: faFilePdf,
        important: false,
      },
      {
        name: 'portfolio.project.mcpDelegateAgents',
        link: 'https://github.com/stevenvo780/MCP-delegate-agents',
        description: 'portfolio.description.mcpDelegateAgents',
        icon: faRobot,
        important: false,
      },
      {
        name: 'portfolio.project.mcpAgents',
        link: 'https://github.com/stevenvo780/MCPagents',
        description: 'portfolio.description.mcpAgents',
        icon: faRobot,
        important: false,
      },
      {
        name: 'portfolio.project.fiarApi',
        link: 'https://github.com/stevenvo780/fiar-api',
        description: 'portfolio.description.fiarApi',
        icon: faNodeJs,
        important: false,
      },
      {
        name: 'portfolio.project.ultimateTerminal',
        link: 'https://github.com/stevenvo780/ultimate-terminal',
        description: 'portfolio.description.ultimateTerminal',
        icon: faTerminal,
        important: false,
      },
      {
        name: 'portfolio.project.cafeteriaDelCaosAPI',
        link: 'https://github.com/stevenvo780/cafeteria-del-caos-api',
        description: 'portfolio.description.cafeteriaDelCaosAPI',
        icon: faNodeJs,
        important: false,
      },
      {
        name: 'portfolio.project.cafeteriaDelCaosFrond',
        link: 'https://github.com/stevenvo780/cafeteria-del-caos-frond',
        description: 'portfolio.description.cafeteriaDelCaosFrond',
        icon: faReact,
        important: false,
      },
      {
        name: 'portfolio.project.cafeteriaDelCaosBot',
        link: 'https://github.com/stevenvo780/cafeteriadelcaos-bot',
        description: 'portfolio.description.cafeteriaDelCaosBot',
        icon: faCogs,
        important: false,
      },
      {
        name: 'portfolio.project.debatesUtil',
        link: 'https://github.com/stevenvo780/debatesUtil',
        description: 'portfolio.description.debatesUtil',
        icon: faCode,
        important: false,
      },
      {
        name: 'portfolio.project.reactTemplate',
        link: 'https://github.com/stevenvo780/TemplateReactBigAPP',
        description: 'portfolio.description.reactTemplate',
        icon: faReact,
        important: false,
      },
      {
        name: 'portfolio.project.auroraCQRS',
        link: 'https://github.com/stevenvo780/auroraCQRS',
        description: 'portfolio.description.auroraCQRS',
        icon: faCogs,
        important: false,
      },
      {
        name: 'portfolio.project.apiNode',
        link: 'https://github.com/stevenvo780/api-node-mongodb',
        description: 'portfolio.description.apiNode',
        icon: faDatabase,
        important: false,
      },
      {
        name: 'portfolio.project.graphQL',
        link: 'https://github.com/stevenvo780/GraphQLExample',
        description: 'portfolio.description.graphQL',
        icon: faNetworkWired,
        important: false,
      },
      {
        name: 'portfolio.project.laravelReact',
        link: 'https://github.com/stevenvo780/LaravelReactREST',
        description: 'portfolio.description.laravelReact',
        icon: faLaravel,
        important: false,
      },
      {
        name: 'portfolio.project.neutrinoSugar',
        link: 'https://github.com/stevenvo780/NeutrinoSugar',
        description: 'portfolio.description.neutrinoSugar',
        icon: faGitAlt,
        important: false,
      },
      {
        name: 'portfolio.project.hackingTool',
        link: 'https://github.com/stevenvo780/capturarUbicacionWhiteHack',
        description: 'portfolio.description.hackingTool',
        icon: faShieldAlt,
        important: false,
      },
      {
        name: 'portfolio.project.cv',
        link: 'https://github.com/stevenvo780/mi-cv',
        description: 'portfolio.description.cv',
        icon: faJsSquare,
        important: false,
      },
    ],
  },
  {
    // Línea de investigación en simulación computacional aplicada a filosofía de la ciencia.
    name: 'portfolio.literatureAndPhilosophy',
    icon: faBook,
    projects: [
      // --- Visibles: investigación/simulación y lógica formal (lo subestimado) ---
      {
        name: 'portfolio.project.estructurasPreontologicas',
        link: 'https://estructuras-preontologicas.vercel.app',
        description: 'portfolio.description.estructurasPreontologicas',
        icon: faAtom,
        important: true,
      },
      {
        name: 'portfolio.project.tesisJacob',
        link: 'https://github.com/stevenvo780/TesisJacobContenidos',
        description: 'portfolio.description.tesisJacob',
        icon: faChartLine,
        important: true,
      },
      {
        name: 'portfolio.project.fenomenologiaUrbana',
        link: 'https://github.com/stevenvo780/FenomenologiaUrbana',
        description: 'portfolio.description.fenomenologiaUrbana',
        icon: faNetworkWired,
        important: true,
      },
      {
        name: 'portfolio.project.unaCartaParaIsaSim',
        link: 'https://github.com/stevenvo780/UnaCartaParaIsa',
        description: 'portfolio.description.unaCartaParaIsaSim',
        icon: faSeedling,
        important: true,
      },
      {
        name: 'portfolio.project.redesNeuronalesFilo',
        link: 'https://github.com/stevenvo780/RedesNeuronalesFilosofiaNeurociencia',
        description: 'portfolio.description.redesNeuronalesFilo',
        icon: faBrain,
        important: true,
      },
      // --- Ocultos: el resto de la línea de investigación/simulación ---
      {
        name: 'portfolio.project.cartaParaIsa',
        link: 'https://github.com/stevenvo780/CartaParaIsa',
        description: 'portfolio.description.cartaParaIsa',
        icon: faBrain,
        important: false,
      },
      {
        name: 'portfolio.project.unMundoParaIsa',
        link: 'https://github.com/stevenvo780/UnMundoParaIsa',
        description: 'portfolio.description.unMundoParaIsa',
        icon: faSeedling,
        important: false,
      },
      {
        name: 'portfolio.project.hiperObjetoSimulaciones',
        link: 'https://github.com/stevenvo780/hiper-objeto-simulaciones',
        description: 'portfolio.description.hiperObjetoSimulaciones',
        icon: faAtom,
        important: false,
      },
      {
        name: 'portfolio.project.logicEducation',
        link: 'https://github.com/stevenvo780/LogicEducation',
        description: 'portfolio.description.logicEducation',
        icon: faGraduationCap,
        important: false,
      },
      {
        name: 'portfolio.project.duoEterno',
        link: 'https://github.com/stevenvo780/duo-eterno',
        description: 'portfolio.description.duoEterno',
        icon: faSeedling,
        important: false,
      },
      {
        name: 'portfolio.project.philosophyArticles',
        link: 'https://medium.com/@stevenvallejo780',
        description: 'portfolio.description.philosophyArticles',
        icon: faBook,
        important: false,
      },
    ],
  },
  {
    name: 'portfolio.mathAndScience',
    icon: faAtom,
    projects: [
      {
        name: 'portfolio.project.universeTraining',
        link: 'https://github.com/stevenvo780/emergentismo-tesis',
        description: 'portfolio.description.universeTraining',
        icon: faAtom,
        important: true,
      },
      {
        name: 'portfolio.project.conwayLife',
        link: 'https://github.com/stevenvo780/emergencia-juego-de-conwey',
        description: 'portfolio.description.conwayLife',
        icon: faPuzzlePiece,
        important: true,
      },
      {
        name: 'portfolio.project.masoSimulation',
        link: 'https://github.com/stevenvo780/teoria-MASOES',
        description: 'portfolio.description.masoSimulation',
        icon: faCogs,
        important: false,
      },
      {
        name: 'portfolio.project.complexityTheory',
        link: 'https://github.com/stevenvo780/complejidad-teoria',
        description: 'portfolio.description.complexityTheory',
        icon: faCogs,
        important: false,
      },
      {
        name: 'portfolio.project.economicSystem',
        link: 'https://github.com/stevenvo780/teoria-sistemas',
        description: 'portfolio.description.economicSystem',
        icon: faChartLine,
        important: false,
      },
      {
        name: 'portfolio.project.cellularCommunication',
        link: 'https://github.com/stevenvo780/teoria-informacion',
        description: 'portfolio.description.cellularCommunication',
        icon: faNetworkWired,
        important: false,
      },
      {
        name: 'portfolio.project.gameTheory',
        link: 'https://github.com/stevenvo780/teoria-de-juegos',
        description: 'portfolio.description.gameTheory',
        icon: faPuzzlePiece,
        important: false,
      },
      {
        name: 'portfolio.project.chaosTheory',
        link: 'https://github.com/stevenvo780/teoria-caos',
        description: 'portfolio.description.chaosTheory',
        icon: faCogs,
        important: false,
      },
      {
        name: 'portfolio.project.decisionTheory',
        link: 'https://github.com/stevenvo780/teoria-desicion',
        description: 'portfolio.description.decisionTheory',
        icon: faChartLine,
        important: false,
      },
      {
        name: 'portfolio.project.ruliatGraph',
        link: 'https://github.com/stevenvo780/teoria-ruliat',
        description: 'portfolio.description.ruliatGraph',
        icon: faNetworkWired,
        important: false,
      },
      {
        name: 'portfolio.project.trainSystem',
        link: 'https://github.com/stevenvo780/SistemaDeTrasporteTrenes',
        description: 'portfolio.description.trainSystem',
        icon: faTrain,
        important: false,
      },
      {
        name: 'portfolio.project.temperatureExperiment',
        link: 'https://github.com/stevenvo780/emergencia-experimento-temperatura',
        description: 'portfolio.description.temperatureExperiment',
        icon: faThermometerHalf,
        important: false,
      },
    ],
  },
  {
    name: 'portfolio.games',
    icon: faGamepad,
    projects: [
      {
        name: 'portfolio.project.cashGame',
        link: 'https://www.cashelresurgirdelosimperios.org/',
        description: 'portfolio.description.cashGame',
        icon: faPuzzlePiece,
        important: true,
      },
      {
        name: 'portfolio.project.escapeRoom',
        link: 'https://www.roblox.com/es/games/13109815288/escape-room-ILS',
        description: 'portfolio.description.escapeRoom',
        icon: faDoorOpen,
        important: false,
      },
      {
        name: 'portfolio.project.robloxGame',
        link: 'https://www.roblox.com/es/games/13343028059/ILS-TEST',
        description: 'portfolio.description.robloxGame',
        icon: faGamepad,
        important: false,
      },
    ],
  },
];

// Se agregan propiedades derivadas para separar proyectos visibles y ocultos.
export const filteredPortfolioCategories = portfolioCategories.map(category => ({
  ...category,
  visibleProjects: category.projects.filter(project => project.important),
  hiddenProjects: category.projects.filter(project => !project.important)
}));
