import {
  faReact,
  faNodeJs,
  faLaravel,
  faGitAlt,
  faJsSquare,
} from '@fortawesome/free-brands-svg-icons';
import {
  faBook,
  faAtom,
  faCode,
  faDatabase,
  faCogs,
  faNetworkWired,
  faChartLine,
  faGamepad,
  faPuzzlePiece,
  faGraduationCap,
  faThermometerHalf,
  faDoorOpen,
  faTrain,
  faShieldAlt,  // Añadir este import
} from '@fortawesome/free-solid-svg-icons';
import { PortfolioCategory } from './types';

export const portfolioCategories: PortfolioCategory[] = [
  {
    name: 'portfolio.programming',
    icon: faCode,
    projects: [
      {
        name: 'portfolio.project.tertuliaFrontend',
        link: 'https://github.com/stevenvo780/tertulialiteraria-frond',
        description: 'portfolio.description.tertuliaFrontend',
        icon: faReact,
        important: true,
      },
      {
        name: 'portfolio.project.tertuliaAPI',
        link: 'https://github.com/stevenvo780/tertulialiteraria-api',
        description: 'portfolio.description.tertuliaAPI',
        icon: faNodeJs,
        important: true,
      },
      {
        name: 'portfolio.project.placetopay',
        link: 'https://github.com/stevenvo780/tienda',
        description: 'portfolio.description.placetopay',
        icon: faChartLine,
        important: true,
      },
      {
        name: 'portfolio.project.reactTemplate',
        link: 'https://github.com/stevenvo780/TemplateReactBigAPP',
        description: 'portfolio.description.reactTemplate',
        icon: faReact,
        important: true,
      },
      {
        name: 'portfolio.project.auroraCQRS',
        link: 'https://github.com/stevenvo780/auroraCQRS',
        description: 'portfolio.description.auroraCQRS',
        icon: faCogs,
        important: true,
      },
      {
        name: 'portfolio.project.apiNode',
        link: 'https://github.com/stevenvo780/api-node-mongodb',
        description: 'portfolio.description.apiNode',
        icon: faDatabase,
        important: true,
      },
      {
        name: 'portfolio.project.graphQL',
        link: 'https://github.com/stevenvo780/GraphQLExample',
        description: 'portfolio.description.graphQL',
        icon: faNetworkWired,
        important: true,
      },
      {
        name: 'portfolio.project.laravelReact',
        link: 'https://github.com/stevenvo780/LaravelReactREST',
        description: 'portfolio.description.laravelReact',
        icon: faLaravel,
        important: true,
      },
      {
        name: 'portfolio.project.cv',
        link: 'https://github.com/stevenvo780/mi-cv',
        description: 'portfolio.description.cv',
        icon: faJsSquare,
        important: true,
      },
      {
        name: 'portfolio.project.neutrinoSugar',
        link: 'https://github.com/stevenvo780/NeutrinoSugar',
        description: 'portfolio.description.neutrinoSugar',
        icon: faGitAlt,
        important: false,
      },
      {
        name: 'portfolio.project.suenoDorado',
        link: 'https://github.com/stevenvo780/SuenoDorado',
        description: 'portfolio.description.suenoDorado',
        icon: faPuzzlePiece,
        important: false,
      },
      {
        name: 'portfolio.project.hardwareProgrammers',
        link: 'https://github.com/stevenvo780/hardwareParaProgramadores',
        description: 'portfolio.description.hardwareProgrammers',
        icon: faCogs,
        important: false,
      },
      {
        name: 'portfolio.project.neuronalLearning',
        link: 'https://github.com/stevenvo780/neuronalLearning',
        description: 'portfolio.description.neuronalLearning',
        important: false,
      },
      {
        name: 'portfolio.project.hackingTool',
        link: 'https://github.com/stevenvo780/capturarUbicacionWhiteHack',
        description: 'portfolio.description.hackingTool',
        icon: faShieldAlt,
        important: true,
      },
    ],
  },
  {
    name: 'portfolio.mathAndScience',
    icon: faAtom,
    projects: [
      {
        name: 'portfolio.project.cellularCommunication',
        link: 'https://github.com/stevenvo780/teoria-informacion',
        description: 'portfolio.description.cellularCommunication',
        icon: faNetworkWired,
        important: true,
      },
      {
        name: 'portfolio.project.chaosTheory',
        link: 'https://github.com/stevenvo780/teoria-caos',
        description: 'portfolio.description.chaosTheory',
        icon: faCogs,
        important: true,
      },
      {
        name: 'portfolio.project.economicSystem',
        link: 'https://github.com/stevenvo780/teoria-sistemas',
        description: 'portfolio.description.economicSystem',
        icon: faChartLine,
        important: true,
      },
      {
        name: 'portfolio.project.universeTraining',
        link: 'https://github.com/stevenvo780/emergentismo-tesis',
        description: 'portfolio.description.universeTraining',
        icon: faAtom,
        important: true,
      },
      {
        name: 'portfolio.project.conwayLife',
        link: 'https://github.com/stevenvo780/emergencia-juego-de-conwey',
        description: 'portfolio.description.conwayLife',
        icon: faPuzzlePiece,
        important: true,
      },
      {
        name: 'portfolio.project.masoSimulation',
        link: 'https://github.com/stevenvo780/teoria-MASOES',
        description: 'portfolio.description.masoSimulation',
        icon: faCogs,
        important: true,
      },
      {
        name: 'portfolio.project.gameTheory',
        link: 'https://github.com/stevenvo780/teoria-de-juegos',
        description: 'portfolio.description.gameTheory',
        icon: faPuzzlePiece,
        important: true,
      },
      {
        name: 'portfolio.project.complexityTheory',
        link: 'https://github.com/stevenvo780/complejidad-teoria',
        description: 'portfolio.description.complexityTheory',
        icon: faCogs,
        important: true,
      },
      {
        name: 'portfolio.project.decisionTheory',
        link: 'https://github.com/stevenvo780/teoria-desicion',
        description: 'portfolio.description.decisionTheory',
        icon: faChartLine,
        important: true,
      },
      {
        name: 'portfolio.project.ruliatGraph',
        link: 'https://github.com/stevenvo780/teoria-ruliat',
        description: 'portfolio.description.ruliatGraph',
        icon: faNetworkWired,
        important: false,
      },
      {
        name: 'portfolio.project.macroMicro',
        link: 'https://github.com/stevenvo780/experimento-macro-micro',
        description: 'portfolio.description.macroMicro',
        icon: faAtom,
        important: false,
      },
      {
        name: 'portfolio.project.trainSystem',
        link: 'https://github.com/stevenvo780/SistemaDeTrasporteTrenes',
        description: 'portfolio.description.trainSystem',
        icon: faTrain,
        important: false,
      },
      {
        name: 'portfolio.project.temperatureExperiment',
        link: 'https://github.com/stevenvo780/emergencia-experimento-temperatura',
        description: 'portfolio.description.temperatureExperiment',
        icon: faThermometerHalf,
        important: false,
      },
      {
        name: 'portfolio.project.vacuumEntropy',
        link: 'https://github.com/stevenvo780/entropia-vacio',
        description: 'portfolio.description.vacuumEntropy',
        icon: faCogs,
        important: false,
      },
    ],
  },
  {
    name: 'portfolio.games',
    icon: faGamepad,
    projects: [
      {
        name: 'portfolio.project.robloxGame',
        link: 'https://www.roblox.com/es/games/13343028059/ILS-TEST',
        description: 'portfolio.description.robloxGame',
        icon: faGamepad,
        important: true,
      },
      {
        name: 'portfolio.project.cashGame',
        link: 'https://www.cashelresurgirdelosimperios.org/',
        description: 'portfolio.description.cashGame',
        icon: faPuzzlePiece,
        important: true,
      },
      {
        name: 'portfolio.project.escapeRoom',
        link: 'https://www.roblox.com/es/games/13109815288/escape-room-ILS',
        description: 'portfolio.description.escapeRoom',
        icon: faDoorOpen,
        important: true,
      },
    ],
  },
  {
    name: 'portfolio.literatureAndPhilosophy',
    icon: faBook,
    projects: [
      {
        name: 'portfolio.project.tertuliaLiteraria',
        link: 'https://www.tertulia-literaria.com/',
        description: 'portfolio.description.tertuliaLiteraria',
        icon: faGraduationCap,
        important: true,
      },
      {
        name: 'portfolio.project.philosophyArticles',
        link: 'https://medium.com/@stevenvallejo780',
        description: 'portfolio.description.philosophyArticles',
        icon: faBook,
        important: true,
      },
    ],
  },
];
