import {
  faPhp,
  faNodeJs,
  faPython,
  faHtml5,
  faCss3Alt,
  faJsSquare,
  faReact,
  faAngular,
  faVuejs,
  faLaravel,
  faDocker,
  faGithub,
  faUnity,
} from '@fortawesome/free-brands-svg-icons';
import {
  faDatabase,
  faServer,
  faCode,
  faCogs,
  faGamepad,
  faProjectDiagram,
  faPencilRuler,
  faBrain,
  faNetworkWired,
  faImage,
  faCloud,
} from '@fortawesome/free-solid-svg-icons';
import { ToolCategory } from './types';

export const tools: ToolCategory[] = [
  {
    category: 'tools.category.backendDevelopment',
    items: [
      { name: 'nodejs', icon: faNodeJs, level: 95 },
      { name: 'typescript', icon: faCode, level: 95 },
      { name: 'nestjs', icon: faCode, level: 90 },
      { name: 'hapi', icon: faCode, level: 85 },
      { name: 'python', icon: faPython, level: 80 },
      { name: 'express', icon: faCode, level: 75 },
      { name: 'php', icon: faPhp, level: 75 },
      { name: 'laravel', icon: faLaravel, level: 70 },
      { name: 'symfony', icon: faPhp, level: 70 },
      { name: 'slim', icon: faPhp, level: 60 },
      { name: 'bash', icon: faCode, level: 65 },
      { name: 'dotnet', icon: faCode, level: 45 },
    ].sort((a, b) => b.level - a.level),
    links: [
      {
        url: 'https://github.com/stevenvo780/tertulialiteraria-api',
        icon: faNodeJs,
      },
      {
        url: 'https://github.com/stevenvo780/api-node-mongodb',
        icon: faNodeJs,
      },
      { url: 'https://github.com/stevenvo780/cafeteria-del-caos-api', icon: faNodeJs },
    ],
  },
  {
    category: 'tools.category.frontendDevelopment',
    items: [
      { name: 'reactjs', icon: faReact, level: 95 },
      { name: 'javascript', icon: faJsSquare, level: 90 },
      { name: 'html', icon: faHtml5, level: 85 },
      { name: 'flask', icon: faPython, level: 80 },
      { name: 'pysimplegui', icon: faPython, level: 78 },
      { name: 'angular', icon: faAngular, level: 75 },
      { name: 'css3', icon: faCss3Alt, level: 80 },
      { name: 'nextjs', icon: faReact, level: 75 },
      { name: 'reactNative', icon: faReact, level: 75 },
      { name: 'laravelBlade', icon: faLaravel, level: 70 },
      { name: 'vuejs', icon: faVuejs, level: 60 },
      { name: 'angular', icon: faAngular, level: 40 },
    ].sort((a, b) => b.level - a.level),
    links: [
      {
        url: 'https://github.com/stevenvo780/tertulialiteraria-frond',
        icon: faReact,
      },
      {
        url: 'https://github.com/stevenvo780/TemplateReactBigAPP',
        icon: faReact,
      },
      { url: 'https://github.com/stevenvo780/cafeteria-del-caos-frond', icon: faReact },
    ],
  },
  {
    category: 'tools.category.devopsAndCloud',
    items: [
      { name: 'git', icon: faGithub, level: 95 },
      { name: 'firebase', icon: faCloud, level: 90 },
      { name: 'linuxHosting', icon: faServer, level: 85 },
      { name: 'googleCloud', icon: faCloud, level: 80 },
      { name: 'render', icon: faCloud, level: 78 },
      { name: 'vercel', icon: faCloud, level: 75 },
      { name: 'rabbitmq', icon: faServer, level: 70 },
      { name: 'cicd', icon: faCogs, level: 65 },
      { name: 'aws', icon: faCloud, level: 60 },
      { name: 'docker', icon: faDocker, level: 55 },
      { name: 'amazonSQS', icon: faServer, level: 30 },
      { name: 'googlePubSub', icon: faServer, level: 30 },
      { name: 'zeroMQ', icon: faServer, level: 30 },
      { name: 'neon', icon: faServer, level: 30 },
      { name: 'azure', icon: faCloud, level: 25 },
    ].sort((a, b) => b.level - a.level),
    links: [
      { url: 'https://github.com/stevenvo780/cafeteriadelcaos-bot', icon: faGithub },
    ],
  },
  {
    category: 'tools.category.databases',
    items: [
      { name: 'MariaDB', icon: faDatabase, level: 95 },
      { name: 'mysql', icon: faDatabase, level: 90 },
      { name: 'postgresql', icon: faDatabase, level: 90 },
      { name: 'graphDB', icon: faDatabase, level: 80 },
      { name: 'neo4j', icon: faDatabase, level: 75 },
      { name: 'mongodb', icon: faDatabase, level: 70 },
      { name: 'redis', icon: faDatabase, level: 65 },
      { name: 'sqlite', icon: faDatabase, level: 60 },
      { name: 'dynamodb', icon: faDatabase, level: 30 },
      { name: 'apacheKafka', icon: faDatabase, level: 70 },
      { name: 'couchDB', icon: faDatabase, level: 60 },
      { name: 'cassandra', icon: faDatabase, level: 60 },
      { name: 'elasticSearch', icon: faDatabase, level: 20 },
    ].sort((a, b) => b.level - a.level),
    links: [],
  },
  {
    category: 'tools.category.aiAndMachineLearning',
    items: [
      { name: 'numpy', icon: faBrain, level: 75 },
      { name: 'tensorflow', icon: faBrain, level: 60 },
      { name: 'huggingface', icon: faNetworkWired, level: 65 },
      { name: 'stableDiffusion', icon: faImage, level: 60 },
      { name: 'cupy', icon: faBrain, level: 70 },
      { name: 'cuda', icon: faCogs, level: 60 },
      { name: 'parallelization', icon: faCogs, level: 60 },
      { name: 'pytorch', icon: faBrain, level: 60 },
      { name: 'keras', icon: faBrain, level: 65 },
      { name: 'pandas', icon: faBrain, level: 75 },
      { name: 'opencv', icon: faImage, level: 60 },
      { name: 'matplotlib', icon: faProjectDiagram, level: 65 }
    ].sort((a, b) => b.level - a.level),
    links: [
      {
        url: 'https://github.com/stevenvo780/emergentismo-tesis',
        icon: faPython,
      },
      {
        url: 'https://github.com/stevenvo780/emergencia-juego-de-conwey',
        icon: faPython,
      },
    ],
  },
  {
    category: 'tools.category.aiTools',
    items: [
      { name: 'chatgpt', icon: faBrain, level: 90 },
      { name: 'githubCopilot', icon: faGithub, level: 85 },
      { name: 'openia', icon: faBrain, level: 80 },
      { name: 'googleCloudAI', icon: faCloud, level: 70 },
      { name: 'deebseek', icon: faBrain, level: 70 },
      { name: 'googleGemini', icon: faCloud, level: 75 },
      { name: 'claude', icon: faBrain, level: 65 },
      { name: 'llama', icon: faBrain, level: 60 },
      { name: 'whisper', icon: faBrain, level: 55 },
    ].sort((a, b) => b.level - a.level),
    links: [
      { url: 'https://github.com/stevenvo780/jarvisIAV2', icon: faBrain },
      { url: 'https://github.com/stevenvo780/mauroLetraCancionesImagenes', icon: faBrain },
    ],
  },
  {
    category: 'tools.category.gameDevelopment',
    items: [
      { name: 'unity', icon: faUnity, level: 80 },
      { name: 'vrAndAR', icon: faGamepad, level: 70 },
      { name: 'roblox', icon: faGamepad, level: 65 },
      { name: 'decentraland', icon: faGamepad, level: 60 },
    ].sort((a, b) => b.level - a.level),
    links: [],
  },
  {
    category: 'tools.category.projectManagement',
    items: [
      { name: 'scrum', icon: faPencilRuler, level: 85 },
      { name: 'advance_documents', icon: faPencilRuler, level: 80 },
      { name: 'trello', icon: faProjectDiagram, level: 70 },
      { name: 'tdd', icon: faPencilRuler, level: 70 },
      { name: 'agile', icon: faPencilRuler, level: 70 },
      { name: 'kanban', icon: faPencilRuler, level: 70 },
      { name: 'jira', icon: faPencilRuler, level: 60 },
      { name: 'clickup', icon: faPencilRuler, level: 55 },
      { name: 'notion', icon: faPencilRuler, level: 50 },
      { name: 'excel', icon: faPencilRuler, level: 35 },

    ].sort((a, b) => b.level - a.level),
    links: [],
  },
];
