import type { Locale } from '@/lib/site';

export const ACTIVITY = {
  es: {
    meta: { title: 'Qué estoy haciendo', description: 'Una constelación de trabajo real: el último año, el último mes y la última semana de Steven Vallejo, con actividad agregada y privacidad.' },
    nav: { back: 'Volver al inicio', current: 'Qué estoy haciendo', language: 'EN', skip: 'Saltar al contenido' },
    eyebrow: 'Qué estoy haciendo / Archivo en movimiento', titleFirst: 'El pulso', titleBridge: 'de lo que', titleLast: 'construyo.',
    intro: 'Un año de ideas que se vuelven realidad. Un día a la vez. Incluso cuando el trabajo sucede detrás de una puerta cerrada.',
    heroNote: 'La huella es pública. El trabajo privado sigue siendo privado.',
    observatory: '01 / Observatorio del tiempo', chartTitle: 'Un día. Una estrella.',
    chartIntro: 'Cada cuerpo es un día. Su luz y tamaño reflejan la actividad registrada. Cambia de escala y recorre el tiempo.',
    stageLabel: 'Escultura cinética de la actividad diaria', stageHint: 'Arrastra para explorar · toca un día',
    geometry: { year: '01 / La constelación', month: '02 / La órbita', week: '03 / El pulso' },
    timelineLabel: 'Recorrer los días', timeline: 'El tiempo, en tus manos', pause: 'Pausar animación', resume: 'Reanudar animación',
    play: 'Reproducir el periodo', stop: 'Detener reproducción', playShort: 'Recorrer el tiempo', stopShort: 'Detener', playCompact: 'Recorrer',
    motion: 'Movimiento', motionPaused: 'En pausa', reduced: 'Vista sin movimiento', dayUnit: 'días', view: 'Explorar',
    chartAccessible: 'Constelación de actividad diaria. Usa las flechas para recorrer los días, Inicio y Fin para ir a los extremos.',
    periods: { week: 'Última semana', month: 'Último mes', year: 'Último año' },
    periodsShort: { week: '7 días', month: '30 días', year: 'Un año' },
    periodLabel: 'Ventana de tiempo', orbitLabel: 'El tiempo deja huella', orbitEmpty: 'Esperando datos reales',
    contributions: 'contribuciones', commits: 'commits', activeDays: 'días con actividad registrada', busiestDay: 'día con más actividad',
    selected: 'Un día en la órbita', selectDay: 'Explorar una fecha', previousDay: 'Día anterior', nextDay: 'Día siguiente',
    selectPrompt: 'Selecciona un punto para explorar ese día.', zeroDay: 'Sin actividad registrada en esta fuente.',
    noNarrative: 'Este registro muestra volumen, no el contenido del trabajo. Los detalles de los proyectos privados se quedan privados.',
    loading: 'Conectando con la actividad…', unavailable: 'Todavía no hay una fuente de actividad conectada.',
    fetchFailed: 'La actividad no pudo cargarse. Puedes volver a intentarlo.', retry: 'Volver a intentar',
    stale: 'Esta sincronización tiene más de 48 horas. La huella puede estar incompleta.', refreshFailed: 'No se pudo actualizar. Se conserva la última sincronización disponible.',
    range: 'Periodo registrado', sync: 'Última sincronización', latest: 'Última actividad registrada', noLatest: 'Sin actividad en este periodo',
    source: 'Fuente', github: 'GitHub · recuentos agregados', journal: 'Registro propio · recuentos agregados',
    timezone: 'Fechas en UTC', legendLow: 'Menos actividad', legendHigh: 'Más actividad', keyboardHint: 'Toca un día · o recórrelos con las flechas',
    diaryEyebrow: '02 / Más allá del número', diaryTitle: 'La huella y su historia.',
    diaryIntro: 'Apuntes que decido compartir sobre lo que voy construyendo, investigando y aprendiendo.',
    noDiary: 'No todo lo que construyo puede contarse en público. Esta huella muestra el ritmo; los detalles privados se quedan conmigo.',
    areas: { engineering: 'Ingeniería', research: 'Investigación', design: 'Diseño', writing: 'Escritura' },
    privacyEyebrow: 'Abierto en lo esencial', privacyTitle: 'Mostrar el ritmo.\nCuidar el detalle.',
    privacyBody: 'Aquí se publican fechas, cantidades, nombres de proyectos que elijo compartir y mis apuntes. El código, los archivos, las rutas internas, los datos personales y los mensajes de commits se quedan privados.',
    measurement: 'Una contribución no equivale a horas de trabajo ni a calidad. Este mapa muestra la actividad registrada por su fuente; no todo lo que hago cabe en Git.',
    footer: 'En movimiento, siempre con intención.',
  },
  en: {
    meta: { title: 'What I’m working on', description: 'A constellation of real work: Steven Vallejo’s last year, month and week, through aggregated activity that respects privacy.' },
    nav: { back: 'Back to home', current: 'What I’m working on', language: 'ES', skip: 'Skip to content' },
    eyebrow: 'What I’m working on / An archive in motion', titleFirst: 'The pulse', titleBridge: 'of what', titleLast: 'I build.',
    intro: 'A year of ideas becoming real. One day at a time. Even when the work happens behind a closed door.',
    heroNote: 'The footprint is public. Private work stays private.',
    observatory: '01 / An observatory of time', chartTitle: 'One day. One star.',
    chartIntro: 'Every body is a day. Its light and size reflect recorded activity. Change the scale and move through time.',
    stageLabel: 'Kinetic sculpture of daily activity', stageHint: 'Drag to explore · touch a day',
    geometry: { year: '01 / The constellation', month: '02 / The orbit', week: '03 / The pulse' },
    timelineLabel: 'Explore the days', timeline: 'Time, in your hands', pause: 'Pause animation', resume: 'Resume animation',
    play: 'Play the period', stop: 'Stop playback', playShort: 'Travel through time', stopShort: 'Stop', playCompact: 'Replay',
    motion: 'Motion', motionPaused: 'Paused', reduced: 'View without motion', dayUnit: 'days', view: 'Explore',
    chartAccessible: 'Daily activity constellation. Use arrow keys to explore dates, Home and End to reach the first and last dates.',
    periods: { week: 'Last week', month: 'Last month', year: 'Last year' },
    periodsShort: { week: '7 days', month: '30 days', year: 'One year' },
    periodLabel: 'Time window', orbitLabel: 'Time leaves a trace', orbitEmpty: 'Waiting for real data',
    contributions: 'contributions', commits: 'commits', activeDays: 'days with recorded activity', busiestDay: 'most active day',
    selected: 'A day in the orbit', selectDay: 'Explore a date', previousDay: 'Previous day', nextDay: 'Next day',
    selectPrompt: 'Select a point to explore that day.', zeroDay: 'No activity recorded by this source.',
    noNarrative: 'This record shows volume, not the content of the work. The details of private projects stay private.',
    loading: 'Connecting to the activity…', unavailable: 'An activity source has not been connected yet.',
    fetchFailed: 'The activity could not be loaded. You can try again.', retry: 'Try again',
    stale: 'This sync is over 48 hours old. The footprint may be incomplete.', refreshFailed: 'Could not refresh. The last available sync is preserved.',
    range: 'Recorded period', sync: 'Last synced', latest: 'Last recorded activity', noLatest: 'No activity in this period',
    source: 'Source', github: 'GitHub · aggregate counts', journal: 'Personal log · aggregate counts',
    timezone: 'Dates in UTC', legendLow: 'Less activity', legendHigh: 'More activity', keyboardHint: 'Touch a day · or explore with arrow keys',
    diaryEyebrow: '02 / Beyond the number', diaryTitle: 'The trace and its story.',
    diaryIntro: 'Notes I choose to share about what I’m building, researching and learning.',
    noDiary: 'Not everything I build can be shared publicly. This trace shows the rhythm; the private details stay with me.',
    areas: { engineering: 'Engineering', research: 'Research', design: 'Design', writing: 'Writing' },
    privacyEyebrow: 'Open where it matters', privacyTitle: 'Show the rhythm.\nProtect the details.',
    privacyBody: 'Dates, counts, project names I choose to share and my notes are published here. Code, files, internal paths, personal data and commit messages remain private.',
    measurement: 'A contribution is not a measure of working hours or quality. This map shows the activity recorded by its source; not everything I do fits into Git.',
    footer: 'In motion, always with intention.',
  },
} satisfies Record<Locale, object>;

export type ActivityCopy = (typeof ACTIVITY)[Locale];
